### ISSUE TITLE
Using add_from_raster on a SpatialPoints instead of a SpatialPointsDataFrame

### ISSUE THREAD

**Issue by choisy** [choisy/sptools#13]
Can we use the `add_from_raster()` function on a `SpatialPoints` object instead of a `SpatialPointsDataFrame` object? If no, should we update this function so that it can deal with `SpatialPoints` objects as well as with `SpatialPointsDataFrame` objects? (I think we should).

**Comment by LucieContamin** [comment]
The function `add_from_raster()` is currently, not working for the `SpatialPoints` object. But, we can update the function for dealing with `SpatialPoints` object, by, if necessary, transforming the object to `SpatialPointsDataFrame` when assigning the value from the raster file. 
I can take care of it if you want.

**Comment by choisy** [comment]
Yes, that would be very useful I think! Let me know if you go for it, otherwise I'll go.

**Comment by LucieContamin** [comment]
I will do it!

**Comment by choisy** [comment]
OK if I do it now?
