### ISSUE TITLE
Bug in points_in_polygon

### ISSUE THREAD

**Issue by choisy** [choisy/sptools#14]
Let's consider the climatic stations in the province of Hanoi:
```
library(sp)
provinces <- sptools::gadm("vietnam", "sp", 1)
hanoi <- subset(provinces, VARNAME_1 == "Ha Noi")
stations <- as(imhen::stations, "Spatial")
```
From the plot, we can see that there are 3 stations in the province of Hanoi:
```
plot(hanoi)
plot(stations, add = TRUE)
```
Yet, the function `points_in_polygons` fails to return 3 points:
```
length(sptools::points_in_polygon(stations, hanoi))
```

**Comment by LucieContamin** [comment]
Resolve in pull-request #15
